### PR TITLE
Some tweaks, pick the ones you like

### PR DESCRIPTION
**Pull request by joaotavora**

### CODE REVIEW

**Comment by casouri** [comment]
Thanks! Good stuff. 

One question though. I'm pretty sure that you know what you are doing, but I couldn't figure out what does 
f292ac2 do.

You said it can help when user is moving quickly. But IIUC eldoc has a idle timer right? On my Emacs it is 0.5 second. So I need to move my point to a symbol and stay for 0.5 second before eldoc timer calls `eldoc-print-current-symbol-info` which displays the childframe. So when I'm moving my point quickly, nothing is shown.

Is my understanding correct? What exactly does f292ac2 do?

I know it a bit troublesome to not only write PR but also answer questions, but I really couldn't figure it out myself...

**Comment by joaotavora** [comment]
> I know it a bit troublesome to not only write PR but also answer questions, but I really couldn't figure it out myself...

Of course you should ask! In fact I don't know why eldoc's idle timer didn't work here.  It was a pragmatic thing and very under-tested. Better not merge it and test yourself and come to your own conclusions.  

The problem happened when scrolling up and down quickly on two lines that had some eldoc-able doc.  In eglot, with pyls.

**Comment by casouri** [comment]
I think I know why, please look at PR #6 (and give it a try?) If it looks good to you, I'll merge that and the other two commits of this PR.

**Comment by joaotavora** [comment]
I've had a quick look and #6 seems like a very good idea.  So merge that instead of f292ac2

**Pull request closed without merging**
