### PR TITLE
Rework eldoc-box--window-side 

### PR DESCRIPTION
**Pull request by dalugm**
On my macOS, when using this line to get the left window, it returns `nil`.

https://github.com/casouri/eldoc-box/blob/e58ecc46996a9c0271e2c3e68c921b6c7cb10026/eldoc-box.el#L329

I guess that's because my Emacs has a padding between `frame-edges` and `window-absolute-pixel-edges`

When there is only one window in my frame:

```elisp
(frame-edges)
;; => (550 176 2230 1173)
(window-absolute-pixel-edges)
;; => (552 178 2228 1155)
```

You can see my window edges are wrapped inside frame.

When using `(window-at-x-y 0 (+ y top))`, I got `nil` instead of the left window.

When using `(window-at-x-y 2 (+ y top))` (here `2` is 552 - 550), I can get the left side window.

---

So first, I want to change the code like this:

```diff
+(let* ((x (- (car (window-absolute-pixel-edges)) (car (frame-edges))))
-(let* ((y (cdr (posn-x-y (posn-at-point))))
        (y (cdr (posn-x-y (posn-at-point))))
        (top (nth 1 (window-absolute-pixel-edges (selected-window))))
+       (left-window (window-at-x-y x (+ y top))))
-       (left-window (window-at-x-y 0 (+ y top))))
   (if (eq left-window (selected-window))
       'left
     'right))
```

But when the active window is the right window, I can't get the padding.

So I decided to change the condition, and it works fine in my machine for two weeks.

### CODE REVIEW

**Comment by casouri** [comment]
Thanks, that makes sense, your updated version makes sense too. Let me know when you are happy with it and ready to merge.

**Comment by dalugm** [comment]
> Let me know when you are happy with it and ready to merge.

It's ready for merge now.

---

ps: The reason I force-pushed is because I change some variables' name before I opened this pr, and I forgot to rename them all... Now it should be good ;)

**Comment by casouri** [comment]
No worries ;-) Merged, thanks!

**Comment by dalugm** [comment]
Thx! I guess it's safe to close this pr now?

**Pull request closed without merging**
